---
- name: Install php-fpm and deps
  ansible.builtin.yum:
    name: "{{ item }}"
    update_cache: True
    state: present
  with_items:
    - php
    - php-fpm
    - php-enchant
    - php-mbstring
    - php-mysqlnd
    - php-process
    - php-xml

- name: restart php-fpm
  ansible.builtin.service:
    name: php-fpm
    state: restarted
