- name: Install the correct PHP-FPM for Centos
  import_tasks: centos.yml
  when: ansible_facts['distribution']|lower == 'centos'
- name: Install the correct PHP-FPM for Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_facts['distribution']|lower == 'ubuntu'
