#cloud-config
users:
  - name: kali
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ${file("~/.ssh/id_rsa.pub")}
package_update: true
package_upgrade: false
packages:
  - nginx
  - mc