# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.box_check_update = false


  config.vm.define "node 2" do |machine|
   machine.vm.hostname = "server"
   machine.vm.network "private_network", ip: "192.168.100.20"
   machine.vm.synced_folder "temp/", "/home/vagrant/temp"
#   machine.vm.network "forwarded_port", guest: 1194, host: 1194
   machine.vm.provision "shell", path: "script2.sh"
  end



  config.vm.define "node 1" do |machine|
   machine.vm.hostname = "client"  
   machine.vm.network "private_network", ip: "192.168.100.10"
   machine.vm.synced_folder "temp/", "/home/vagrant/temp"
   machine.vm.provision "shell", path: "script.sh"
  end





  # config.vm.hostname = "server"  
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"
  # config.vm.synced_folder ".", "/vagrant", disabled: true
  # config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
