
- name: Disable default pool
  ansible.builtin.command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
  when: ansible_facts['os_family']|lower == 'centos'

- name: Copy php-fpm configuration
  ansible.builtin.template:
    src: wordpress_centos.conf
    dest: "/etc/php-fpm.d/"
  when: ansible_facts['os_family']|lower == 'centos'

- name: Start php-fpm Service
  ansible.builtin.service:
    name: php-fpm
    state: started
    enabled: yes
  when: ansible_facts['os_family']|lower == 'centos'