apiVersion: v1
kind: ServiceAccount
metadata:
  name: diag-sa
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diag-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: diag-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: diag-clusterrole
subjects:
- kind: ServiceAccount
  name: diag-sa
  namespace: dev
---
apiVersion: v1
kind: Pod
metadata:
  name: diag-pod
  namespace: dev
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command: ["sleep", "8400"]
  serviceAccountName: diag-sa
