apiVersion: v1
kind: Service
metadata:
 name: wordpress
 namespace: dev
spec:
 selector:
   app: wordpress
 ports:
   - protocol: TCP
     port: 80
     targetPort: 80
 type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: wordpress
 namespace: dev
spec:
 replicas: 1
 selector:
   matchLabels:
     app: wordpress
 template:
   metadata:
     labels:
       app: wordpress
   spec:
     containers:
       - name: wordpress
         image: dockerhub.timeweb.cloud/wordpress:latest
         env:
           - name: WORDPRESS_DB_HOST
             value: mysql.dev.svc.cluster.local
           - name: WORDPRESS_DB_PASSWORD
             value: test_password
           - name: WORDPRESS_DB_USER
             value: root
           - name: WORDPRESS_DB_NAME
             value: mysql