apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mysql-pvc
 namespace: dev
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 256Mi
 storageClassName: storage
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: dev
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: mysql
 namespace: dev
spec:
 replicas: 1
 selector:
   matchLabels:
     app: mysql
 template:
   metadata:
     labels:
       app: mysql
   spec:
     containers:
       - name: mysql
         image: dockerhub.timeweb.cloud/library/mysql:latest
         env:
         - name: MYSQL_ROOT_PASSWORD
           value: test_password
         volumeMounts:
           - name: mysql-storage
             mountPath: /var/lib/mysql
     volumes:
       - name: mysql-storage
         persistentVolumeClaim:
           claimName: mysql-pvc
