- name: Install the correct DB for Centos
  import_tasks: centos.yml
  when: ansible_facts['distribution']|lower == 'centos'

- name: Install the correct DB for Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_facts['distribution']|lower == 'ubuntu'
