- name: Install Ubuntu DB
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: True
    state: present
  with_items:
    - mysql-server
    - mysql-client
    - python3-mysqldb
    - python3-pymysql

- name: Start Mysql Service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name: Create Mysql configuration file
  ansible.builtin.template:
    src: my.cnf.j2
    dest: "/etc/mysql/conf.d/my.cnf"
#  notify: restart mysql

- name: Restart mysql service
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: Sets the root password
  ansible.builtin.mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Removes all anonymous user accounts
  ansible.builtin.mysql_user:
    name: ''
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

