version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/root_db_pass # root password from secrets
      MYSQL_DATABASE: ${MYSQL_DATABASE} # env for database name
    secrets:
      - root_db_pass
    volumes:
      - ./mysql_db:/var/lib/mysql # mount mysql to host
    restart: always
    networks:
      - backend
  app:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME} # env for wordpress db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER} # env for wordpress db user
      WORDPRESS_DB_PASSWORD: /run/secrets/wp_db_pass # password for user wordpress db from secrets
    secrets:
      - wp_db_pass
    volumes:
      - ./wp_data:/var/www/html # wordpress data to host
    depends_on:
      - db
    networks:
      - backend
      - frontend

  proxy:
    image: nginx
    volumes:
      - ./nginx/config:/etc/nginx/conf.d # Nginx config to host 
    networks:
      - frontend
networks:
  backend: # network for db and app
  frontend: # network for proxy

secrets:
  root_db_pass:
    file: root_db_pass.txt
  wp_db_pass:
    file: db_root_password.txt
